apiVersion: v1
kind: Pod
metadata:
  name: guestbook-ui
  namespace: argo-app-2
  labels:
    app: guestbook-ui33

spec:
  containers:
    - name: guestbook-u33
      image: gcr.io/google-samples/gb-frontend:v5

      ports:
        - containerPort: 80

      # resources:
      #   requests:
      #     cpu: "100m"
      #     memory: "128Mi"
      #   limits:
      #     cpu: "500m"
      #     memory: "256Mi"
